<?php

return [
    'positions' => [
        'title' => 'Chuc vu',
        'subtitle' => 'Quan tri danh muc chuc vu trong he thong',
        'service' => 'hr',
        'resource' => 'positions',
        'legacy_prefix' => 'chucvu',
        'legacy_name' => 'chucvu',
        'permission' => ['view' => 'xem_chucvu', 'create' => 'them_chucvu', 'update' => 'sua_chucvu', 'delete' => 'xoa_chucvu'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
    ],
    'assignments' => [
        'title' => 'Phan cong',
        'subtitle' => 'Quan tri dieu dong nhan su va phan cong cong viec',
        'service' => 'hr',
        'resource' => 'assignments',
        'legacy_prefix' => 'phancong',
        'legacy_name' => 'phancong',
        'permission' => ['view' => 'xem_phancong', 'create' => 'them_phancong', 'update' => 'sua_phancong', 'delete' => 'xoa_phancong'],
    ],
    'insurances' => [
        'title' => 'Bao hiem',
        'subtitle' => 'Quan tri bao hiem nhan vien trong he thong',
        'service' => 'hr',
        'resource' => 'insurances',
        'legacy_prefix' => 'baohiem',
        'legacy_name' => 'baohiem',
        'permission' => ['view' => 'xem_baohiem', 'create' => 'them_baohiem', 'update' => 'sua_baohiem', 'delete' => 'xoa_baohiem'],
    ],
    'leave-requests' => [
        'title' => 'Nghi phep',
        'subtitle' => 'Quan tri don nghi phep trong he thong',
        'service' => 'hr',
        'resource' => 'leave-requests',
        'legacy_prefix' => 'nghiphep',
        'legacy_name' => 'nghiphep',
        'permission' => ['view' => 'xem_nghiphep', 'create' => 'them_nghiphep', 'update' => 'sua_nghiphep', 'delete' => 'xoa_nghiphep'],
        'auto_fill_ma_nv' => true,
    ],
    'reward-records' => [
        'title' => 'Khen thuong ky luat',
        'subtitle' => 'Quan tri cac quyet dinh thuong phat trong he thong',
        'service' => 'hr',
        'resource' => 'reward-discipline-records',
        'legacy_prefix' => 'khenthuong',
        'legacy_name' => 'khenthuong',
        'permission' => ['view' => 'xem_khenthuong', 'create' => 'them_khenthuong', 'update' => 'sua_khenthuong', 'delete' => 'xoa_khenthuong'],
    ],
    'reward-types' => [
        'title' => 'Loai khen thuong ky luat',
        'subtitle' => 'Quan tri danh muc loai thuong phat',
        'service' => 'hr',
        'resource' => 'reward-discipline-types',
        'legacy_prefix' => 'loaikhenthuong',
        'legacy_name' => 'loaikhenthuong',
        'permission' => ['view' => 'xem_khenthuong', 'create' => 'them_khenthuong', 'update' => 'sua_khenthuong', 'delete' => 'xoa_khenthuong'],
    ],
    'employee-profiles' => [
        'title' => 'Ho so nhan vien',
        'subtitle' => 'Quan tri ho so ca nhan trong he thong',
        'service' => 'hr',
        'resource' => 'employee-profiles',
        'legacy_prefix' => 'hosocanhan',
        'legacy_name' => 'hosocanhan',
        'permission' => ['view' => 'xem_nhanvien', 'create' => 'them_hoso', 'update' => 'sua_nhanvien', 'delete' => 'xoa_nhanvien'],
        'file_fields' => ['Anh'],
    ],
    'contracts' => [
        'title' => 'Hop dong',
        'subtitle' => 'Quan tri hop dong lao dong trong he thong',
        'service' => 'payroll',
        'resource' => 'contracts',
        'legacy_prefix' => 'hopdong',
        'legacy_name' => 'hopdong',
        'permission' => ['view' => 'xem_hopdong', 'create' => 'them_hopdong', 'update' => 'sua_hopdong', 'delete' => 'xoa_hopdong'],
    ],
    'salary-bands' => [
        'title' => 'Ngach luong',
        'subtitle' => 'Quan tri he thong ngach luong',
        'service' => 'payroll',
        'resource' => 'salary-bands',
        'legacy_prefix' => 'ngachluong',
        'legacy_name' => 'ngachluong',
        'permission' => ['view' => 'xem_ngachluong', 'create' => 'xem_ngachluong', 'update' => 'xem_ngachluong', 'delete' => 'xem_ngachluong'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
    ],
    'salary-grades' => [
        'title' => 'Bac luong',
        'subtitle' => 'Quan tri cac bac luong trong he thong',
        'service' => 'payroll',
        'resource' => 'salary-grades',
        'legacy_prefix' => 'bacluong',
        'legacy_name' => 'bacluong',
        'permission' => ['view' => 'xem_bacluong', 'create' => 'xem_bacluong', 'update' => 'xem_bacluong', 'delete' => 'xem_bacluong'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
    ],
    'accounts' => [
        'title' => 'Tai khoan',
        'subtitle' => 'Quan tri tai khoan dang nhap va thong tin truy cap',
        'service' => 'hr',
        'resource' => 'accounts',
        'legacy_prefix' => 'taikhoan',
        'legacy_name' => 'taikhoan',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'them_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'xoa_taikhoan'],
    ],
    'roles' => [
        'title' => 'Vai tro',
        'subtitle' => 'Quan tri vai tro he thong',
        'service' => 'hr',
        'resource' => 'roles',
        'legacy_prefix' => 'vaitro',
        'legacy_name' => 'vaitro',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'features' => [
        'title' => 'Chuc nang',
        'subtitle' => 'Quan tri danh muc quyen/chuc nang he thong',
        'service' => 'hr',
        'resource' => 'features',
        'legacy_prefix' => 'chucnang',
        'legacy_name' => 'chucnang',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'account-roles' => [
        'title' => 'Gan vai tro tai khoan',
        'subtitle' => 'Quan tri vai tro cua tung tai khoan',
        'service' => 'hr',
        'resource' => 'account-roles',
        'legacy_prefix' => 'gantaikhoanvaitro',
        'legacy_name' => 'gantaikhoanvaitro',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'audit-logs' => [
        'title' => 'Nhat ky he thong',
        'subtitle' => 'Theo doi phien dang nhap va lich su truy vet',
        'service' => 'hr',
        'resource' => 'session-audits',
        'legacy_prefix' => 'auditlog',
        'legacy_name' => 'auditlog',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'xem_taikhoan', 'update' => 'xem_taikhoan', 'delete' => 'xem_taikhoan'],
        'read_only' => true,
    ],
];